/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  discoverySidebar: [
    {
      type: 'category',
      label: 'Getting started',
      items: ['discovery/discovery'],
    },
          {
      type: 'category',
      label: 'Intro',
      items: ['discovery/discovery'],
    },
  ],

  fundraisingSidebar: [
    {
      type: 'category',
      label: 'Getting started',
      items: ['fundraising/fundraising'],
    },
        {
      type: 'category',
      label: 'Intro',
      items: ['fundraising/fundraising'],
    },
    {
      type: 'doc',
      id: 'fundraising/fundraising',
      label: 'Primary'

    }
  ],
};

module.exports = sidebars;
